# Generated by Django 2.1.7 on 2019-06-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('nutriscore', models.CharField(max_length=1)),
                ('stores', models.CharField(max_length=200)),
                ('image', models.URLField(default='image')),
                ('brand', models.CharField(max_length=100)),
                ('calories', models.IntegerField(null=True)),
                ('lipids', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('proteins', models.FloatField(null=True)),
                ('salts', models.FloatField(null=True)),
                ('url_off', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
    ]
